---
title: "p8105_hw2_ht2630"
author: "Haotian Tang"
date: "`r Sys.Date()`"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
```

---

Problem 1

Clean data in pols_month.csv file.
```{r clean pols}

pols_df = 
  read_csv("fivethirtyeight_datasets/pols-month.csv") |>
  
  janitor::clean_names() |>
  
  separate(mon, into = c("year", "month", "day"), sep = "-") |>
  
  mutate(year = as.integer(year),
         month = as.integer(month),
         day = as.integer(day)) |>
  
  mutate(month = factor(month, labels = month.name)) |>
  
  mutate(president = case_when(
    prez_gop == 1 ~ "gop",
    prez_dem == 1 ~ "dem",
    prez_dem == 2 ~ "gop",
  )) |>
  
  select(-prez_dem, -prez_gop, -day)
```

Clean data in snp.csv file. 

```{r clean snp}

snp_df = 
  read_csv("fivethirtyeight_datasets/snp.csv") |>
  
  janitor::clean_names()|>

  separate(date, into = c("month", "day", "year"), sep = "/") |>
  
  mutate(month = as.integer(month),
         day = as.integer(day),
         year = as.integer(year)) |>
  
  mutate(year = if_else(year < 100, year + 2000, year)) |>
  
  mutate(year = if_else(year > 2023, year - 100, year)) |>
  
  mutate(month = month.name[as.integer(month)]) |>
  
  arrange(year, month) |>
  
  select(year, month, close)

```

Tidy and merge them

```{r clean unemployment}

unemployment_df = 
  read_csv("fivethirtyeight_datasets/unemployment.csv") |>
  
  pivot_longer(cols = -Year, names_to = "month", values_to = "unemployment_rate") |>

  rename(year = Year) |>
  
  mutate(month = match(month, month.abb),
         month = month.name[month]) |>
  
  arrange(year, month)
```

```{r merge them together}

first_merge = left_join(pols_df, snp_df, by = c("year", "month"))

merged_data = left_join(first_merge, unemployment_df, by = c("year", "month"))

```

The final data contains the specific date and pols, snp, and unemployment data. And we can also notice "NA" in the dataset, which means the data of those variables are missing.  

---

Problem 2

```{r Mr. Trash Wheel}

mr_trash_wheel_df = read_excel("Trash_wheel_data.xlsx", sheet = 'Mr. Trash Wheel') |>
  
  janitor::clean_names() |>
  
  rename(dumpster_id = dumpster) |>
  
  mutate(trash_wheel_name = "Mr. Trash Wheel") |>
  
  select(1, trash_wheel_name, everything()) |>
  
  select(-ncol(mr_trash_wheel_df):-(ncol(mr_trash_wheel_df)-1)) |>
  
  mutate(date = day(ymd(date))) |>
  
  mutate(homes_powered = (weight_tons * 500) / 30)
  
```

```{r Professor Trash Wheel}

professor_trash_wheel_df = read_excel("Trash_wheel_data.xlsx", sheet = 'Professor Trash Wheel') |>
  
  janitor::clean_names() |>
  
  rename(dumpster_id = dumpster) |>
  
  mutate(trash_wheel_name = "Professor Trash Wheel") |>
  
  select(1, trash_wheel_name, everything()) |>
  
  mutate(date = day(ymd(date))) |>
  
  mutate(homes_powered = (weight_tons * 500) / 30)

```

```{r}

gwynnda_trash_wheel_df = read_excel("Trash_wheel_data.xlsx", sheet = 'Gwynnda Trash Wheel') |>
  
  janitor::clean_names() |>
  
  rename(dumpster_id = dumpster) |>
  
  mutate(trash_wheel_name = "Gwynnda Trash Wheel") |>
  
  select(1, trash_wheel_name, everything()) |>
  
  mutate(date = day(ymd(date))) |>
  
  mutate(homes_powered = (weight_tons * 500) / 30)

```


